### ISSUE TITLE
key-spacing

### ISSUE THREAD

**Issue by hzoo** [babel/eslint-config-babel#16]
this should be on?

Ref https://github.com/babel/babel/pull/5296#discussion_r101171389

```js
assert.deepEqual(referencePaths[0].node.loc.start, { line: 1, column:28 });
```

**Comment by loganfsmyth** [comment]
I'm 100% for this rule. Since these changes necessitate a major version bump, how would you feel about adding it to the `.eslintrc` in the Babel repo until we get a few more rules? There are a bunch more I feel like we should enable, but adding them one at a time to this repo will get old pretty quick, and adding them to the main repo first means we can PR them with the fixes at the same time.
