### ISSUE TITLE
Any chance of relaxing linebreak-style?

### ISSUE THREAD

**Issue by motiz88** [babel/eslint-config-babel#7]
Git contains logic to bridge line break styles between platforms. By default, repos on Windows are checked out with CRLF (but checked in with LF). Enforcing LF here makes working with `eslint-config-babel`-managed repos on Windows painful by default, for no clear benefit - as Git will normalize line endings by the time any changes make it to CI.

**Comment by danez** [comment]
Imho git should be configured to do nothing to files and just checkout files as is. And in the projects we have .editorconfig so that your editor/ide knows which lineendings to use. It seems to me more dangerous to rely on some tool maybe doing something to sourcefiles on the fly than configuring your environment to always use `LF`. 
If we would relax it then CI also wouldn't catch wrong linebreaks.

**Comment by motiz88** [comment]
I suppose that's true. In this case the projects should definitely have this set in `.gitattributes`.
